Hope I'm doing this right.
Arks-Layer/PSO2ENPatchCSV pull request #120
Opened 2017-05-31 07:27 UTC by memegreen

I still don't know how to really use GitHub. But whatever, right?

2017-05-31 11:54 UTC, SynthSy requested changes

2017-05-31 11:54 UTC, SynthSy commented on Story/Episode 2/un_025090.csv
> +un_025090_0130#0,"""I got it! Master! You're stronger than anyone I know, so \""Master\"" it is!"""
Shishou is closer to Teacher than master. You could use Master, but in this case, Teacher would fit better.

2017-05-31 15:19 UTC, memegreen commented on Story/Episode 2/un_025090.csv
> +un_025090_0130#0,"""I got it! Master! You're stronger than anyone I know, so \""Master\"" it is!"""
Gotcha. I was also throwing around "Coach" and the like before falling back on "Master." Wanted to hear some thoughts before I attempt another push.

2017-06-01 22:49 UTC, SynthSy approved these changes

2017-06-01 22:50 UTC, merged