NGS story quest dialogue intro
Arks-Layer/PSO2ENPatchCSV pull request #1442
Opened 2021-06-13 00:13 UTC by Cavistus

figured i should get this evaluated before i get ahead of myself

2021-06-13 19:52 UTC, SynthSy requested changes

2021-06-13 19:52 UTC, SynthSy commented on Story/msc_010050.csv
> +msc_010050_0030#0,"""“A Pettas Sword, huh... Yeah, I can handle this much!"""
We're not using global enemy names, so pettas -> pedas

2021-06-13 19:52 UTC, SynthSy commented on Story/msc_010100.csv
> +msc_010100_0010#0,"""Welcome to Aelio Town! On behalf of everyone in the village, welcome."""
Aelio -> Aerio

2021-06-13 19:52 UTC, SynthSy commented on Story/msc_010130.csv
> +msc_010130_0100#0,"""And on it, we're in a village called Aelio Town."""
Aelio -> Aerio

2021-06-13 19:52 UTC, SynthSy commented on Story/msc_010130.csv
> +msc_010130_0160#0,"""That Pettas Sword you were fighting earlier? It's actually one of the smaller ones."""
Pettas -> Pedas

2021-06-13 19:52 UTC, SynthSy commented on Story/msc_010130.csv
> +msc_010130_0260#0,"""Meteorn is what we call the folks that crash down from outer space inside one of those pods like the one you were found in."""
I think here, it should be "Meteorn are" rather than "Meteron is".

2021-06-13 19:52 UTC, SynthSy commented on Story/msc_010140.csv
> +msc_010142_0040#0,"""It's not everyone, but I had some of the Aelio Town reisdents join us."""
Aelio -> Aerio

2021-06-13 19:52 UTC, SynthSy commented on Story/msc_010144.csv
> +msc_010142_0040#0,"""It's not everyone, but I had some of the Aelio Town reisdents join us."""
Aelio -> Aerio

2021-06-13 19:52 UTC, SynthSy commented on Story/msc_010144.csv
> +msc_010144_0160#0,"""You looked like you were handling yourself pretty well against that Pettas Sword before I showed up."""
Pettas -> Pedas

2021-06-13 19:52 UTC, SynthSy commented on Story/msc_010190.csv
> +msc_010190_0060#0,"""The DOLLS are gone, but... so is all of Aelio Town..."""
Aelio -> Aerio

2021-06-13 19:52 UTC, SynthSy commented on Story/msc_010220.csv
> +msc_010220_0010#0,"""You're coming from Aelio Town, yes?"""
Aelio -> Aerio

2021-06-15 09:44 UTC, SynthSy requested changes

2021-06-15 09:44 UTC, SynthSy commented on Story/msc_011350.csv
> +msc_011350_0010#0,"""As you heard, within the Razor Woods,"""
Resol Forest

2021-06-15 09:44 UTC, SynthSy commented on Story/msc_011350.csv
> +msc_011350_0120#0,"""The mission to send support into Razor Woods, in particular, will be considerably dangerous."""
Resol Forest

2021-06-15 09:44 UTC, SynthSy commented on Story/msc_011330.csv
> +msc_011330_0080#0,"""While patrolling the Razor Woods, Bruder's team went silent..."""
Resol Forest

2021-06-15 10:01 UTC, Cavistus commented on Story/msc_011350.csv
> +msc_011350_0010#0,"""As you heard, within the Razor Woods,"""
fixed

2021-06-15 10:01 UTC, Cavistus commented on Story/msc_011350.csv
> +msc_011350_0120#0,"""The mission to send support into Razor Woods, in particular, will be considerably dangerous."""
fixed

2021-06-15 10:01 UTC, Cavistus commented on Story/msc_011330.csv
> +msc_011330_0080#0,"""While patrolling the Razor Woods, Bruder's team went silent..."""
fixed

2021-06-15 19:45 UTC, merged