Ru: any quest and much more
Arks-Layer/PSO2ENPatchCSV pull request #154
Opened 2017-06-22 08:43 UTC by Sinitsaa

2017-06-22 23:47 UTC, alama commented on translated files/Quests/base protection/.deleteme
> +
For what?

2017-06-22 23:47 UTC, alama commented on translated files/Quests/Luzer/.deleteme
> +
For what?

2017-06-22 23:47 UTC, alama commented on translated files/Quests/Elder/.deleteme
> +
For what?

2017-06-23 09:58 UTC, Sinitsaa commented on translated files/Quests/base protection/.deleteme
> +
Classification of emergency quests.
A little later I will remove it.

2017-06-23 09:58 UTC, Sinitsaa commented on translated files/Quests/Luzer/.deleteme
> +
Classification of emergency quests.
A little later I will remove it.

2017-06-23 09:58 UTC, Sinitsaa commented on translated files/Quests/Elder/.deleteme
> +
Classification of emergency quests.
A little later I will remove it.

2017-06-27 20:25 UTC, alama requested changes

2017-06-27 20:25 UTC, alama commented on translated files/UI/ui_pet.csv
> +DirectBuy_EggSynthesisNum_Confirm_Msg#0,"""以下のアイテムを$(0)SG(通常100SG)で購入し、<br>合成可能数を５個回復させます。<br>Are you sure?<br><yellow><br>※連続購入時、購入１回目～９回目までは<br>\u3000価格が割引されますが、回数が増えると<br>\u3000割引率が下がります。<c><br>※N
Really? are you just copying and paste from the check script output

2017-06-27 20:25 UTC, alama commented on translated files/UI/ui_pet.csv
> +DirectBuy_EggSynthesisNum_Success_Msg#0,"""$(0)の<br>合成可能数を５つ追加しました。<br><br><yellow>※この５回分は、エッグ合成時の<br>\u3000獲得経験値量にボーナスがつきます。<c><br><br>※Number of purchases resets at 5am every day." =~ "$(0)の<br>合成可
What the fuck are you doing?

2017-06-27 20:29 UTC, Sinitsaa commented on translated files/UI/ui_pet.csv
> +DirectBuy_EggSynthesisNum_Success_Msg#0,"""$(0)の<br>合成可能数を５つ追加しました。<br><br><yellow>※この５回分は、エッグ合成時の<br>\u3000獲得経験値量にボーナスがつきます。<c><br><br>※Number of purchases resets at 5am every day." =~ "$(0)の<br>合成可
I'm trying to correct mistakes. Sometimes I accidentally create new ones.

2017-06-28 00:39 UTC, Sinitsaa commented
Merge, please

2017-06-28 02:35 UTC, merged