Merge pull request #1 from Arks-Layer/ES
Arks-Layer/PSO2ENPatchCSV pull request #446
Opened 2018-02-08 08:35 UTC by Reixaldo

Es: Actualization?

2018-02-08 15:57 UTC, alama commented
Why are you moving some files and have no changes in them?

2018-02-12 00:56 UTC, TheBlazter requested changes
Numerosos errores ortográficos (LICENCIA se escribe con 2 C no con CS o SC) y cambios innecesarios (Super Difícil es nombre propio de la dificultad)

2018-02-12 00:56 UTC, TheBlazter commented on Misc/np_010851.csv
> +skit03#0,"""¿Que es darker?"""
Darker debe tener nombre con mayúscula inicial (nombre propio de tipo de enemigo

2018-02-12 00:56 UTC, TheBlazter commented on Misc/quest_00050640.csv
> +a4#0,"""Poseer una licensia de super dificil"""
esta mal escrito: licencia

2018-02-12 00:56 UTC, TheBlazter commented on Misc/quest_00050730.csv
> +a3#0,"""Poseer una licensia de super dificil"""
y se repite lo de licencia

2018-02-12 00:56 UTC, TheBlazter commented on Misc/quest_00050780.csv
> +a3#0,"""Poseer una licensia de super dificil"""
y una vez mas licencia

2018-02-12 00:56 UTC, TheBlazter commented on Misc/quest_00080230.csv
> +a3#0,"""Poseer una licensia de super dificil"""
y mas licencia

2018-02-12 00:56 UTC, TheBlazter commented on Misc/quest_00050790.csv
> +a3#0,"""Poseer una licensia de super dificil"""
licencia

2018-02-12 00:56 UTC, TheBlazter commented on Misc/quest_00080250.csv
> +a3#0,"""Poseer una licensia de super dificil"""
continua licencia

2018-02-12 00:56 UTC, TheBlazter commented on Quests/Buster Quests/quest_00050750.csv
> +a3#0,"""Poseer una licensia de super dificil"""
no voy a repetir mas lo de licen**c**ia

2018-02-12 01:42 UTC, Reixaldo commented on Quests/Buster Quests/quest_00050750.csv
> +a3#0,"""Poseer una licensia de super dificil"""
tehe~

2018-02-12 02:14 UTC, TheBlazter approved these changes

2018-02-12 02:14 UTC, merged