Es: Corrections
Arks-Layer/PSO2ENPatchCSV pull request #451
Opened 2018-02-15 15:18 UTC by Reixaldo

ewe

2018-02-15 22:01 UTC, TheBlazter requested changes
Revisar ortografía igual otras notas, recuerda que el verbo Fingir es con g no j asi que la palabra finjiendo esta mal escrita, es fingiendo

2018-02-15 22:01 UTC, TheBlazter commented on UI/ui_item.csv
> +pet_inheritance#0,"""Evolucionar mascotaペット進化"""
Cuidado con esto

2018-02-15 22:01 UTC, TheBlazter commented on UI/ui_amusement.csv
> +PrizeExchangeRadioButton#0,"""Puede equiarse"""
Cuidado, con equiparse

2018-02-15 22:01 UTC, TheBlazter commented on UI/ui_amusement.csv
> +ComeOutBetsCancel#0,"""Apuestas cnceladas."""
canceladas

2018-02-15 22:12 UTC, TheBlazter requested changes

2018-02-15 22:12 UTC, TheBlazter commented on Dialogue/Mid-Mission/cm_032390.csv
> +skit01#8,"""/ci1 1 está es la información del último fragmento.<br>Experimentos, temas y palabras desagradables están volando alrededor."""
Es principio de linea así que esta debe ir en mayúscula inicial igualmente así hay varias, o hiciste el masivo sin hacer diferenciación de mayúsculas y minúsculas.

2018-02-15 22:12 UTC, TheBlazter commented on Dialogue/Mid-Mission/cm_032202.csv
> +skit01#0,"""¡Muuu! está niebla...<br>Los dos eviten el suelo.<br>Continúen por el techo!"""
Después de signo de admiración va con mayúscula inicial

2018-02-15 22:17 UTC, TheBlazter commented on UI/ui_amusement.csv
> +ComeOutBetsCancel#0,"""Apuestas cnceladas."""
vuelve y juega recuerda chequear tu ortografía si haces masivos canceladas esta mal escrito

2018-02-15 22:19 UTC, TheBlazter requested changes

2018-02-15 22:19 UTC, TheBlazter commented on Dialogue/Mid-Mission/cm_032380.csv
> +skit01#8,"""/ci1 1 está es la información del último fragmento.<br>Experimentos, temas y palabras desagradables están volando alrededor."""
Este es principio de linea "está" debe ser con mayúscula inicial.

2018-02-16 05:42 UTC, TheBlazter commented
Revisa duplicados
Files/np_012420.csv
Files/np_010260.csv

2018-02-16 05:43 UTC, Reixaldo commented on UI/ui_item.csv
> +pet_inheritance#0,"""Evolucionar mascotaペット進化"""
correjido

2018-02-16 05:43 UTC, Reixaldo commented on UI/ui_amusement.csv
> +PrizeExchangeRadioButton#0,"""Puede equiarse"""
correjido

2018-02-16 17:10 UTC, TheBlazter requested changes

2018-02-16 17:10 UTC, TheBlazter commented on Dialogue/Mid-Mission/ii_js_apc_boss_5026.csv
> +IncidentJsApcBegin#6,"""/ci2 1 A-aaah! You came at the perfect time! Help, Por favor ayudame!"""
Parcialmente en español

2018-02-16 17:10 UTC, TheBlazter commented on Dialogue/Mid-Mission/ii_js_apc_boss_5032.csv
> +IncidentJsApcBegin#6,"""/ci2 1 A-aaah! You came at the perfect time! Help, Por favor ayudame!"""
Parcialmente en español

2018-02-16 17:10 UTC, TheBlazter commented on Dialogue/Mid-Mission/ii_js_apc_boss_5038.csv
> +IncidentJsApcBegin#6,"""/ci2 1 A-aaah! You came at the perfect time! Help, Por favor ayudame!"""
Parcialmente en español

2018-02-16 17:10 UTC, TheBlazter commented on Dialogue/np_012420.csv
>  favs_after_020#0,"""Bueno, entonces, mi amig@!<br>Good Summoner Life!"""
Parcialmente en español

2018-02-16 17:12 UTC, TheBlazter requested changes

2018-02-16 17:12 UTC, TheBlazter commented on Dialogue/Lobby/np_014780.csv
> +11_voice_NPC_5478_103#0,"""Oh, ¡Lo encontre! \u3000Guardian<br>¡Hey!\u3000Finjiendo no finjir"""
Aun no se corrige Fingiendo

2018-02-18 01:33 UTC, Reixaldo commented on Dialogue/Mid-Mission/cm_032202.csv
> +skit01#0,"""¡Muuu! está niebla...<br>Los dos eviten el suelo.<br>Continúen por el techo!"""
correjido

2018-02-18 01:33 UTC, Reixaldo commented on Dialogue/Lobby/np_014780.csv
> +11_voice_NPC_5478_103#0,"""Oh, ¡Lo encontre! \u3000Guardian<br>¡Hey!\u3000Finjiendo no finjir"""
correjido

2018-02-18 03:08 UTC, Reixaldo commented
Estoy en ello...

2018-02-18 18:00 UTC, alama commented on .gitignore
> +Dialogue/Mid-Mission/ii_key_and_lock.csv
What is this?

2018-02-18 18:27 UTC, Reixaldo commented on .gitignore
> +Dialogue/Mid-Mission/ii_key_and_lock.csv
really i don't have any idea

2018-02-18 18:49 UTC, TheBlazter requested changes
Aun siguen y se van acumulando numerosos descuidos, por favor reparar pronto.

2018-02-18 18:49 UTC, TheBlazter commented on Dialogue/Mid-Mission/ii_abd_clone_apc.csv
> +NpcComOnBegin#2,"""Oh, uhm... Arks?...Wait, it isn't?!<br>It's impersonating Arks...<br>Uh, Por favor intercept!"""
Aun sigue en spanglish

2018-02-18 18:49 UTC, TheBlazter commented on Dialogue/Mid-Mission/ii_castle_town_terror.csv
> +NpcComOnBegin#0,"""Pajhadu-lin have appeared in the área, but their movements are... Odd. Everyone should move to intercept them, but Ten cuidado."""
Spanglish

2018-02-18 18:49 UTC, TheBlazter commented on Dialogue/Mid-Mission/ii_castle_town_terror.csv
> +NpcComOnBegin#1,"""Pajhadu-lin have appeared in the área, but their movements are... Odd. Everyone should move to intercept them, but Ten cuidado."""
More spanglish

2018-02-18 18:49 UTC, TheBlazter commented on Dialogue/Mid-Mission/ii_dwarfhome_defense.csv
> +NpcComOnFailure#1,"""The settlements have been annihilated... Unfortunately, there's nothing we can do anymore. Regresa a la misión principal."""
and again

2018-02-18 18:49 UTC, TheBlazter commented on Dialogue/np_npc_chcontrade02.csv
> +00_01#0,"""opción 1"""
Why...

2018-02-18 18:49 UTC, TheBlazter commented on UI/ui_tutorial.csv
> +wh_config#0,"""System / opciónes"""
Mayúscula inicial

2018-02-18 18:49 UTC, TheBlazter commented on UI/ui_title_text.csv
> +CharaSelectMenu_Setting#0,"""opciónes adicionales"""
Mayúscula inicial

2018-02-18 18:49 UTC, TheBlazter commented on UI/ui_title_text.csv
> +Menu_3#0,"""opciónes"""
Mayúscula inicial

2018-02-18 18:49 UTC, TheBlazter commented on UI/ui_selectmenu_text.csv
> +UserCommand_Item1#0,"""Cambiar info. Encima del PJ"""
info entra como abreviatura de información así que la regla de mayúscula después de punto seguido no iría en este.

2018-02-18 18:49 UTC, TheBlazter commented on UI/ui_mainmode.csv
> +MainMenu_Config#0,"""opciónes"""
Mayúscula inicial

2018-02-18 18:49 UTC, TheBlazter commented on UI/ui_mainmode.csv
> +MainMenu_System_Option#0,"""opciónes"""
Mayúscula inicial

2018-02-18 18:49 UTC, TheBlazter commented on UI/ui_mainmode.csv
> +Priority_Title#0,"""opciónes de pantalla principal"""
Mayúscula inicial

2018-02-18 18:49 UTC, TheBlazter commented on UI/ui_mainmode.csv
> +CharaMenu_Friend07#0,"""opciónes de pantalla principal"""
Mayúscula inicial

2018-02-18 18:49 UTC, TheBlazter commented on UI/ui_mainmode.csv
> +CharaMenu_Friend08#0,"""opciónes del grupo"""
Mayúscula inicial

2018-02-18 18:49 UTC, TheBlazter commented on UI/ui_mainmode.csv
> +PartyConfigTab03#0,"""opciónes de clave"""
Mayúscula inicial

2018-02-18 18:49 UTC, TheBlazter commented on UI/ui_mainmode.csv
> +MenuOther#0,"""opciónes de privacidad"""
Mayúscula inicial

2018-02-18 18:49 UTC, TheBlazter commented on UI/ui_mainmode.csv
> +EditOpenSetting#0,"""opciónes de privacidad"""
Mayúscula inicial

2018-02-18 18:49 UTC, TheBlazter commented on UI/ui_mainmode.csv
> +Esthetic_Menu_PopTitle#0,"""opciónes adicionales"""
Mayúscula inicial

2018-02-18 18:49 UTC, TheBlazter commented on UI/ui_mainmode.csv
> +TitleText1#0,"""opciónes de misión"""
Mayúscula inicial

2018-02-18 18:49 UTC, TheBlazter commented on UI/config.csv
> +MenuTreeDirection#0,"""opciónes de Dirección"""
Mayúscula inicial... en todo -_-

2018-02-18 18:49 UTC, TheBlazter commented on UI/common.csv
> +Type_1#0,"""opciónes"""
Mayúscula inicial

2018-02-18 19:12 UTC, Reixaldo commented on Dialogue/Mid-Mission/ii_abd_clone_apc.csv
> +NpcComOnBegin#2,"""Oh, uhm... Arks?...Wait, it isn't?!<br>It's impersonating Arks...<br>Uh, Por favor intercept!"""
si me pones a corregir todo el spanglish que toco jamas acabare este Pr...

2018-02-18 19:14 UTC, Reixaldo commented on Dialogue/np_npc_chcontrade02.csv
> +00_01#0,"""opción 1"""
correjido

2018-02-18 19:14 UTC, Reixaldo commented on UI/ui_tutorial.csv
> +wh_config#0,"""System / opciónes"""
correjido

2018-02-18 19:14 UTC, Reixaldo commented on UI/ui_title_text.csv
> +CharaSelectMenu_Setting#0,"""opciónes adicionales"""
Corregido.

2018-02-18 19:14 UTC, Reixaldo commented on UI/ui_title_text.csv
> +Menu_3#0,"""opciónes"""
Corregido.

2018-02-18 19:15 UTC, Reixaldo commented on UI/ui_selectmenu_text.csv
> +UserCommand_Item1#0,"""Cambiar info. Encima del PJ"""
chanfles o.o

2018-02-18 19:15 UTC, Reixaldo commented on UI/ui_mainmode.csv
> +MainMenu_Config#0,"""opciónes"""
Corregido.

2018-02-18 19:15 UTC, Reixaldo commented on UI/ui_mainmode.csv
> +MainMenu_System_Option#0,"""opciónes"""
Corregido.

2018-02-18 19:15 UTC, Reixaldo commented on UI/ui_mainmode.csv
> +Priority_Title#0,"""opciónes de pantalla principal"""
Corregido.

2018-02-18 19:16 UTC, Reixaldo commented on UI/ui_mainmode.csv
> +CharaMenu_Friend07#0,"""opciónes de pantalla principal"""
Corregido.

2018-02-18 19:16 UTC, Reixaldo commented on UI/ui_mainmode.csv
> +CharaMenu_Friend08#0,"""opciónes del grupo"""
Corregido.

2018-02-18 19:16 UTC, Reixaldo commented on UI/ui_mainmode.csv
> +PartyConfigTab03#0,"""opciónes de clave"""
Corregido.

2018-02-18 19:16 UTC, Reixaldo commented on UI/ui_mainmode.csv
> +MenuOther#0,"""opciónes de privacidad"""
Corregido.

2018-02-18 19:17 UTC, Reixaldo commented on UI/ui_mainmode.csv
> +EditOpenSetting#0,"""opciónes de privacidad"""
Corregido.

2018-02-18 19:17 UTC, Reixaldo commented on UI/ui_mainmode.csv
> +TitleText1#0,"""opciónes de misión"""
Corregido.

2018-02-18 19:17 UTC, Reixaldo commented on UI/config.csv
> +MenuTreeDirection#0,"""opciónes de Dirección"""
Corregido.

2018-02-18 19:17 UTC, Reixaldo commented on UI/common.csv
> +Type_1#0,"""opciónes"""
Corregido.

2018-02-19 00:06 UTC, TheBlazter requested changes
Just Why

2018-02-19 00:06 UTC, TheBlazter commented on UI/ui_esthetic_text.csv
> +Result_4#0,"""Sistemaエラーが発生しました。<br>時間をおいてお試しください。"""
Why

2018-02-19 00:06 UTC, TheBlazter commented on UI/ui_craft.csv
> +RoomMove_Result_SystemError#0,"""Sistemaエラーにより、<br>マイルームの移動に失敗しました。"""
Why

2018-02-19 00:06 UTC, TheBlazter commented on UI/ui_mainmode.csv
> +Standard_Result_SystemError#0,"""Sistemaエラーにより処理が失敗しました。"""
and Why

2018-02-19 00:06 UTC, TheBlazter commented on UI/ui_title_text.csv
> +ErrorOther#0,"""Sistemaエラーが発生したため<br>名前を変更できませんでした。"""
??????????????

2018-02-19 00:06 UTC, TheBlazter commented on UI/ui_tutorial.csv
> +wh_storyboard_questrank#0,"""Misión / ストーリークエストの難易度"""
....................... ok

2018-02-19 00:06 UTC, TheBlazter commented on UI/ui_tutorial.csv
> +wh_qu_defense_friend#0,"""Misión / 防衛結果"""
nothing more to say

2018-02-19 00:06 UTC, TheBlazter commented on UI/ui_tutorial.csv
> +wh_campaignquest#0,"""Misión / キャンペーンクエスト"""
.......

2018-02-19 00:53 UTC, Reixaldo commented on UI/ui_tutorial.csv
> +wh_storyboard_questrank#0,"""Misión / ストーリークエストの難易度"""
¿Are bad? e_e

2018-02-19 01:40 UTC, Reixaldo commented on UI/ui_tutorial.csv
> +wh_qu_defense_friend#0,"""Misión / 防衛結果"""
fue mi intención hacer eso ewe

2018-02-19 03:37 UTC, Reixaldo commented on UI/ui_tutorial.csv
> +wh_campaignquest#0,"""Misión / キャンペーンクエスト"""
expiration date are a duplicate line....

2018-02-19 04:46 UTC, TheBlazter requested changes
Mas cambios

2018-02-19 04:46 UTC, TheBlazter commented on Dialogue/Mid-Mission/heatup.csv
> +FortAttack1#1,"""Detecto un portal cercano... las reacciones de los darks está aumentando!"""
darkers

2018-02-19 04:46 UTC, TheBlazter commented on Dialogue/Mid-Mission/ii_abd_clone_apc.csv
> +NpcComOnBegin#2,"""Oh, uhm... Arks?...Wait, it isn't?!<br>It's impersonating Arks...<br>Uh, Por favor intercept!"""
................... mmm ok, pero tarde o temprano hay que repararlo -_-"

2018-02-19 04:46 UTC, TheBlazter commented on Dialogue/Mid-Mission/ii_annihilation_bomb_wave.csv
> +NpcComOnSuccess#1,"""Las lecturas hostiles han desaparecido atraves del Ignix readings. Bien, puedes regresar a tus regular duties."""
es poquito spanglish. Puedes, si?

2018-02-19 04:46 UTC, TheBlazter commented on Dialogue/Mid-Mission/ii_annihilation_bomb_wave.csv
>  NpcComOnBegin2#2,"""There's a bad, bad hostile causing this somewhere around here! Por favor find and defeat it!"""
Se que aquí hay que corregir pero queda como pendiente

2018-02-19 04:46 UTC, TheBlazter commented on Dialogue/Mid-Mission/ii_areaboss_dp.csv
>  NpcComOnSuccess#0,"""/face2 Enemy readings have disappeared,<br>thanks to your hard work."""
pendientes para futura reparación

2018-02-19 04:46 UTC, TheBlazter commented on Dialogue/Mid-Mission/ii_areaboss_dp.csv
>  NpcComOnFailure#1,"""Tch, they've taken a beating.<br>Teleporting them to Campship."""
pendientes para futura reparación

2018-02-19 04:46 UTC, TheBlazter commented on Dialogue/Mid-Mission/ii_areaboss_dp2.csv
>  NpcComOnSuccess#0,"""/face2 Enemy readings have disappeared,<br>thanks to your hard work."""
pendientes para futura reparación

2018-02-19 04:46 UTC, TheBlazter commented on Dialogue/Mid-Mission/ii_boss_ahl_nyau_ev_rare.csv
>  NpcComOnBegin#3,"""This is an emergency directive. Por favor repel the hostile that has appeared."""
pendientes para futura reparación

2018-02-19 04:46 UTC, TheBlazter commented on Dialogue/Mid-Mission/ii_boss_ahl_nyau_ev_rare.csv
>  NpcComOnBegin_Other#3,"""This is an emergency directive. Por favor repel the hostile that has appeared."""
pendientes para futura reparación

2018-02-19 04:46 UTC, TheBlazter commented on Dialogue/Mid-Mission/ii_boss_ahl_nyau_ev_rare.csv
>  NpcComOnBegin_Darker#3,"""This is an emergency directive. Por favor repel the hostile that has appeared."""
pendientes para futura reparación

2018-02-19 04:46 UTC, TheBlazter commented on Dialogue/Mid-Mission/ii_collect_goods_a.csv
> +NpcComOnBeginAtRareCase#0,"""Discovered Fosil de insectos we'd like to<br>study! Nuestro tiempo es corto. Todos,<br>please bring the items in question<br>to the pods quickly!"""
Mas spanglish

2018-02-19 04:46 UTC, TheBlazter commented on Dialogue/Mid-Mission/ii_collect_goods_a.csv
> +Collect1st#0,"""Confirmed target Almacen.<br>Please, keep it up!"""
ok...

2018-02-19 04:46 UTC, TheBlazter commented on Dialogue/Mid-Mission/ii_dwarf_defense.csv
> +NpcComOnAfterBegin#0,"""/face4 We can't let that Gilnas be<br>attacked! Please, protect it<br>so the Lillipans can escape!<br>Ten cuidado not to damage it while protecting it!"""
mas spanglish

2018-02-19 04:46 UTC, TheBlazter commented on Dialogue/Mid-Mission/ii_dwarf_junkspot.csv
> +NpcComOnFailure#0,"""Is the Lillipan alright?...Excuse me. It's unfortunate, but you've failed to protect it. Por favor, vuelve a la misión principal"""
y mas

2018-02-19 04:46 UTC, TheBlazter commented on Dialogue/Mid-Mission/ii_dwarf_junkspot.csv
>  NpcComOnBeginNext#0,"""I see... it seems like the Lillipan is searching for some kind of treasure. Por favor keep it as safe as you can."""
pendientes para futura reparación

2018-02-19 04:46 UTC, TheBlazter commented on Dialogue/Mid-Mission/ii_dwarf_junkspot.csv
>  NpcComOnArrivalFirst#0,"""The Lillipan has arrived at its destination. Hostiles are converging on your location. Ten cuidado, and Por favor keep the Lillipan safe."""
pendientes para futura reparación

2018-02-19 04:46 UTC, TheBlazter commented on Dialogue/Mid-Mission/ii_dwarfhome_defense.csv
> +NpcComOnFailure#1,"""The settlements have been annihilated... Desafortunadamente, no hay nada que podamos hacer. Regresa a la misión principal."""
ok hay poco spanglish puedes repararlo?

2018-02-19 04:46 UTC, TheBlazter commented on Dialogue/Mid-Mission/ii_ev_boss_rematch.csv
> +TrialBeginMsg#0,"""Emergency directive! Derrotar a<br>newly-appeared $(0)!"""
ok...

2018-02-19 04:46 UTC, TheBlazter commented on Dialogue/Mid-Mission/ii_escape_rare_enemy_ahl.csv
> +NpcComOnBegin#0,"""Confirmed a major $(0)<br>outbreak. Por favor get the data of<br>these rare beings before they flee."""
too much mix

2018-02-19 04:46 UTC, TheBlazter commented on Dialogue/Mid-Mission/ii_ev_js_apc.csv
> +NpcComOnDownB#1,"""That Arks' burden is really weighing<br>'em down. I suggest you retreat if<br>there's another screw-up, alright?"""
pendientes para futura reparación

2018-02-19 04:46 UTC, TheBlazter commented on Dialogue/Mid-Mission/ii_ev_js_apc.csv
> +NpcComOnDownA#2,"""Ummm... Your coordination<br>isn't so good... Por favor try<br>to work together a bit more."""
pendientes para futura reparación

2018-02-19 04:46 UTC, TheBlazter commented on Dialogue/Mid-Mission/ii_ev_partner_boss.csv
> +NpcComOnBegin#2,"""Oh, it seems newcomers have<br>arrived! Por favor Derrotar a todos!"""
pendientes para futura reparación

2018-02-19 04:46 UTC, TheBlazter commented on Dialogue/Mid-Mission/ii_js_apc_boss_0000.csv
>  IncidentJsApcBegin#12,"""/toge /ci1 1 We can do this! We're Arks! I might be old, but I can't be stopped!"""
???

2018-02-19 04:46 UTC, TheBlazter commented on Dialogue/Mid-Mission/ii_js_apc_boss_0000.csv
> +IncidentJsApcBeginEvo#11,"""/ci3 1 está atmosfera... Maybe a newcomer appeared... Por favor presta atención y preparate."""
poco spanglish

2018-02-19 04:46 UTC, TheBlazter commented on Dialogue/Mid-Mission/ii_js_apc_boss_5026.csv
> +IncidentJsApcBeginEvo#11,"""/ci3 1 está atmosfera... Maybe a newcomer appeared... Por favor presta atención y preparate."""
"Maybe a newcomer appeared" es un poco recurrente puedes corregir esto?

2018-02-19 04:46 UTC, TheBlazter commented on Dialogue/Mid-Mission/ii_js_apc_boss_5026.csv
>  IncidentJsApcBegin#12,"""/toge /ci1 1 We can do this! We're Arks! I might be old, but I can't be stopped!"""
Pendiente para futura revision

2018-02-19 04:46 UTC, TheBlazter commented on Dialogue/Mid-Mission/ii_js_apc_boss_8012.csv
>  IncidentJsApcFailure#4,"""/mn7 Sorry... It's impossible to continue the battle. Let me retreat. Por favor forgive me!"""
hay que revisar esto

2018-02-19 04:46 UTC, TheBlazter commented on Dialogue/Mid-Mission/ii_js_apc_boss_8012.csv
>  IncidentJsApcBegin#12,"""/toge /ci1 1 We can do this! We're Arks! I might be old, but I can't be stopped!"""
hay que revisar esto

2018-02-19 04:46 UTC, TheBlazter commented on Dialogue/Mid-Mission/ii_js_apc_boss_8012.csv
> +IncidentJsApcBeginEvo#11,"""/ci3 1 está atmosfera... Maybe a newcomer appeared... Por favor presta atención y preparate."""
y lo de el newcomer es comun

2018-02-19 04:46 UTC, TheBlazter commented on Dialogue/Mid-Mission/ii_pamper_jack_box.csv
> +NpcComOnPreBegin#2,"""This heat source sure<br>is strange! Por favor<br>be extra careful!"""
???

2018-02-19 04:46 UTC, TheBlazter commented on Dialogue/Mid-Mission/ii_pit_ahl.csv
> +NpcComOnBegin#2,"""Ahhh, a trap, it's a trap! Please,<br>Derrotar a enemies first, then<br>use a device to escape!"""
hay que revisar esto

2018-02-19 04:46 UTC, TheBlazter commented on Dialogue/Mid-Mission/ii_pse_defense.csv
> +NpcComOnBegin#0,"""Todos, Por favor defend the<br>energized crystals! Por favor be<br>aware that crystal power will<br>fade if no Arks are nearby!"""
mas spanglish

2018-02-19 04:46 UTC, TheBlazter commented on Orders/Client/co01020031.csv
>  Explanation#0,"""Would you believe a lot of ARKS are<br>extremely disorganized? Keep yourself<br>organized to avoid getting suffocated<br>with clutter. Keep things neat and tidy!<br><br>Everyone has
pendiente

2018-02-19 04:46 UTC, TheBlazter commented on Orders/Client/co01040600.csv
> +Explanation#0,"""I'm Gerard, a civilian biologist researching<br>the various fauna of nearby planets, but<br>the ARKS research fácilities do not grant<br>me enough freedom. I intend to write a<br>rep
pendiente..... y "fácilities"? pero si ni siquiera esta en español xD

2018-02-19 04:46 UTC, TheBlazter commented on Orders/Client/co04063401.csv
> +Explanation#0,"""<yellow>Esta orden ya no está disponible.<br>si ya has completado está orden,<br>you can turn it in.<br>If you have not completed this<br>order, Por favor cancel it as you will<br>no
pendiente

2018-02-19 04:46 UTC, TheBlazter commented on Orders/Client/co04063403.csv
> +Explanation#0,"""<yellow>Esta orden ya no está disponible.<br>si ya has completado está orden,<br>you can turn it in.<br>If you have not completed this<br>order, Por favor cancel it as you will<br>no
pendiente

2018-02-19 04:46 UTC, TheBlazter commented on Orders/Client/co04063404.csv
> +Explanation#0,"""<yellow>Esta orden ya no está disponible.<br>si ya has completado está orden,<br>you can turn it in.<br>If you have not completed this<br>order, Por favor cancel it as you will<br>no
pendiente

2018-02-19 04:46 UTC, TheBlazter commented on Orders/Client/co04063405.csv
> +Explanation#0,"""<yellow>Esta orden ya no está disponible.<br>si ya has completado está orden,<br>you can turn it in.<br>If you have not completed this<br>order, Por favor cancel it as you will<br>no
pendiente

2018-02-19 04:46 UTC, TheBlazter commented on Orders/Client/co04063406.csv
> +Explanation#0,"""<yellow>Esta orden ya no está disponible.<br>si ya has completado está orden,<br>you can turn it in.<br>If you have not completed this<br>order, Por favor cancel it as you will<br>no
pendiente

2018-02-19 04:46 UTC, TheBlazter commented on Orders/Daily/Complete/do01030300.csv
> +Explanation#0,"""Order delivery for all Arks!<br><br>Clear a certain Misión as many times as<br>you'd like!<br><br>Your payment/reward will be given to<br>you upon completion! The more you do,<br>the
pendiente

2018-02-19 04:46 UTC, TheBlazter commented on Orders/Daily/Complete/do01030301.csv
> +Explanation#0,"""Order delivery for all Arks!<br><br>Clear a certain Misión as many times as<br>you'd like!<br><br>Your payment/reward will be given to<br>you upon completion! The more you do,<br>the
pendiente

2018-02-19 04:46 UTC, TheBlazter commented on Orders/Daily/Complete/do01030302.csv
> +Explanation#0,"""Order delivery for all Arks!<br><br>Clear a certain Misión as many times as<br>you'd like!<br><br>Your payment/reward will be given to<br>you upon completion! The more you do,<br>the
pendiente

2018-02-19 04:46 UTC, TheBlazter commented on Orders/Daily/Complete/do01030303.csv
> +Explanation#0,"""Order delivery for all Arks!<br><br>Clear a certain Misión as many times as<br>you'd like!<br><br>Your payment/reward will be given to<br>you upon completion! The more you do,<br>the
pendiente

2018-02-19 04:46 UTC, TheBlazter commented on Orders/Daily/Complete/do01030305.csv
> +Explanation#0,"""Order delivery for all Arks!<br><br>Clear a certain Misión as many times as<br>you'd like!<br><br>Your payment/reward will be given to<br>you upon completion! The more you do,<br>the
pendiente

2018-02-19 04:46 UTC, TheBlazter commented on Orders/Daily/Complete/do01030306.csv
> +Explanation#0,"""Order delivery for all Arks!<br><br>Clear a certain Misión as many times as<br>you'd like!<br><br>Your payment/reward will be given to<br>you upon completion! The more you do,<br>the
pendiente

2018-02-19 04:46 UTC, TheBlazter commented on Orders/Daily/Complete/do01030307.csv
> +Explanation#0,"""Order delivery for all Arks!<br><br>Clear a certain Misión as many times as<br>you'd like!<br><br>Your payment/reward will be given to<br>you upon completion! The more you do,<br>the
La linea se repite varias veces se podria reparar

2018-02-19 04:46 UTC, TheBlazter commented on Orders/Daily/Defeat/do01020311.csv
>  Explanation#0,"""Orden para todos los miembros ARKS:<br><br>Defeat as many as you can of a certain<br>type of enemy!<br><br>Your payment/reward will be given to<br>you upon completion! The more you<b
Es una linea común que en otras ordenes ya esta en español podrías repararla

2018-02-19 04:46 UTC, TheBlazter commented on Orders/Daily/Defeat/do01020404.csv
>  Explanation#0,"""Orden para todos los miembros ARKS:<br><br>Defeat as many as you can of a certain<br>type of enemy!<br><br>Your payment/reward will be given to<br>you upon completion! The more you<b
igual

2018-02-19 04:46 UTC, TheBlazter commented on Story/Episode 5/st_054135.csv
> +st_054135_0040#0,"""Bueno, ¡Entonses puedes generalizar el análisis de este mecanismo!"""
*Entonces

2018-02-19 04:46 UTC, TheBlazter commented on Story/Episode 5/un_050030.csv
> +un_050030_0170#0,"""¡TODO está CUBIERTO POR UNA SOLA CLASE! ¿¡No ES ESO GRANDIOSO!?"""
la linea es en caps sostenida

2018-02-19 04:46 UTC, TheBlazter commented on UI/ui_tutorial.csv
> +wh_craft_top#0,"""Crafteo / クラフトメニュー"""
Cuidado con esto

2018-02-19 04:46 UTC, TheBlazter commented on UI/ui_tutorial.csv
> +wh_craft_search#0,"""Crafteo / クラフター検索"""
Recuerda las traducciones de lineas parciales no se traducen lo que falta, quedan parcialmente traducidas

2018-02-19 04:46 UTC, TheBlazter commented on UI/ui_title_text.csv
> +CharaSelectMenu_Setting#0,"""opciónes adicionales"""
pos no lo veo corregido

2018-02-19 04:46 UTC, TheBlazter commented on UI/ui_shop.csv
> +SgShopGuide#0,"""<c f0df60>購入するアイテムを選択してください。「Actualización manual de la lista<c><pict StarGem><c f0df60>」で、すぐに商品リストを更新できます。<c>"""
Las traducciones parciales son parciales

2018-02-19 04:46 UTC, TheBlazter commented on UI/ui_qu_eternal.csv
> +TitleNoDead#0,"""No morir mas de $(0) ves(ces)!"""
Ves= Ver / Vez =Veces

2018-02-19 05:34 UTC, Reixaldo commented on UI/ui_qu_eternal.csv
> +TitleNoDead#0,"""No morir mas de $(0) ves(ces)!"""
:facepalm: :man_facepalming:

2018-02-19 05:36 UTC, Reixaldo commented on Dialogue/Mid-Mission/heatup.csv
> +FortAttack1#1,"""Detecto un portal cercano... las reacciones de los darks está aumentando!"""
Darkers, nombre propio

2018-02-19 05:37 UTC, Reixaldo commented on Dialogue/Mid-Mission/ii_annihilation_bomb_wave.csv
> +NpcComOnSuccess#1,"""Las lecturas hostiles han desaparecido atraves del Ignix readings. Bien, puedes regresar a tus regular duties."""
no tengo idea que es eso del ignix xd

2018-02-19 05:37 UTC, Reixaldo commented on Dialogue/Mid-Mission/ii_areaboss_dp.csv
>  NpcComOnSuccess#0,"""/face2 Enemy readings have disappeared,<br>thanks to your hard work."""
¿Nani?

2018-02-19 05:40 UTC, Reixaldo commented on Dialogue/Mid-Mission/ii_dwarfhome_defense.csv
> +NpcComOnFailure#1,"""The settlements have been annihilated... Desafortunadamente, no hay nada que podamos hacer. Regresa a la misión principal."""
corregido

2018-02-19 05:46 UTC, Reixaldo commented on Dialogue/Mid-Mission/ii_js_apc_boss_5026.csv
> +IncidentJsApcBeginEvo#11,"""/ci3 1 está atmosfera... Maybe a newcomer appeared... Por favor presta atención y preparate."""
corregido

2018-02-19 05:47 UTC, Reixaldo commented on Dialogue/Mid-Mission/ii_js_apc_boss_8012.csv
>  IncidentJsApcFailure#4,"""/mn7 Sorry... It's impossible to continue the battle. Let me retreat. Por favor forgive me!"""
lo dices... por que ese archivo tiene ingles?... o hay algo mal en la linea?

2018-02-19 05:53 UTC, Reixaldo commented on UI/ui_tutorial.csv
> +wh_craft_search#0,"""Crafteo / クラフター検索"""
lo se ewe

2018-02-19 16:05 UTC, TheBlazter commented on Dialogue/Mid-Mission/ii_js_apc_boss_8012.csv
>  IncidentJsApcFailure#4,"""/mn7 Sorry... It's impossible to continue the battle. Let me retreat. Por favor forgive me!"""
por el ingles obvio

2018-02-20 15:31 UTC, Reixaldo commented on Dialogue/Mid-Mission/ii_areaboss_dp.csv
>  NpcComOnSuccess#0,"""/face2 Enemy readings have disappeared,<br>thanks to your hard work."""
why

2018-02-20 17:03 UTC, merged