Es: cositas
Arks-Layer/PSO2ENPatchCSV pull request #459
Opened 2018-02-22 16:42 UTC by Reixaldo

2018-02-22 18:47 UTC, TheBlazter requested changes

2018-02-22 18:47 UTC, TheBlazter commented on UI/ui_amusement.csv
> +PrizeExchangeTitleMenu#0,"""Menú de la tienda"""
Menú en español lleva tilde

2018-02-22 18:47 UTC, TheBlazter commented on UI/ui_mainmode.csv
> +VisiphonMenu_LoginStamp#0,"""Sellos de conección"""
se escribe conexión, conección no existe

2018-02-22 18:47 UTC, TheBlazter commented on UI/ui_mainmode.csv
> +LoginStampTitle#0,"""Sellos de conección"""
conexión 
La manera correcta de denominar el ‘acto y efecto de conectar’ cualquier aparato es “conexión” —con “x”―. Se escribe con esta letra por su etimología, pues “conexión” viene del |latín “connexĭo”, que se escribía, como puedes ver, con “x”.

2018-02-23 04:57 UTC, Reixaldo commented on UI/ui_amusement.csv
> +PrizeExchangeTitleMenu#0,"""Menú de la tienda"""
pero... si ese fue el cambio... estaba colocando la Tildé!

2018-02-23 05:03 UTC, Reixaldo commented on UI/ui_mainmode.csv
> +VisiphonMenu_LoginStamp#0,"""Sellos de conección"""
Chanfles...

2018-02-23 06:00 UTC, merged