Es: check
Arks-Layer/PSO2ENPatchCSV pull request #477
Opened 2018-03-08 07:08 UTC by Reixaldo

2018-03-08 21:15 UTC, TheBlazter requested changes

2018-03-08 21:15 UTC, TheBlazter commented on Orders/Client/EP4/co04037013.csv
> +Explanation#0,"""やあ、マイフレンド！<br>愛する子供達の成育は順調かい？<br>どの子にも分け隔てなく<br>愛情を注いでいると思うけど<br>僕にその成長ぶりを見せて欲しいんだ！<br>そうだな、今回は<br>君とトリムが共に戦う姿を<br>モニターさせてもらえないかな？<br><yellow>※ Objetivos enemigos Nv.61+ usando<br>at
Trim > Torim

2018-03-08 21:15 UTC, TheBlazter commented on Orders/Client/EP4/co04037014.csv
> +Explanation#0,"""やあ、マイフレンド！<br>愛する子供達の成育は順調かい？<br>どの子にも分け隔てなく<br>愛情を注いでいると思うけど<br>僕にその成長ぶりを見せて欲しいんだ！<br>そうだな、今回は<br>君とサリィが共に戦う姿を<br>モニターさせてもらえないかな？<br><yellow>※ Objetivos enemigos Nv.61+ usando<br>at
Sari > Cery

2018-03-08 21:15 UTC, TheBlazter commented on Orders/Client/EP4/co04037019.csv
> +Explanation#0,"""やあ、マイフレンド！<br>愛する子供達の成育は順調かい？<br>どの子にも分け隔てなく<br>愛情を注いでいると思うけど<br>僕にその成長ぶりを見せて欲しいんだ！<br>そうだな、今回は<br>君とシンクロウが共に戦う姿を<br>モニターさせてもらえないかな？<br><yellow>※ Objetivos enemigos Nv.61+ usando<br>
Synchworm > Synchro

2018-03-10 16:54 UTC, Reixaldo commented on Orders/Client/EP4/co04037019.csv
> +Explanation#0,"""やあ、マイフレンド！<br>愛する子供達の成育は順調かい？<br>どの子にも分け隔てなく<br>愛情を注いでいると思うけど<br>僕にその成長ぶりを見せて欲しいんだ！<br>そうだな、今回は<br>君とシンクロウが共に戦う姿を<br>モニターさせてもらえないかな？<br><yellow>※ Objetivos enemigos Nv.61+ usando<br>
Corregido.

2018-03-10 16:54 UTC, Reixaldo commented on Orders/Client/EP4/co04037014.csv
> +Explanation#0,"""やあ、マイフレンド！<br>愛する子供達の成育は順調かい？<br>どの子にも分け隔てなく<br>愛情を注いでいると思うけど<br>僕にその成長ぶりを見せて欲しいんだ！<br>そうだな、今回は<br>君とサリィが共に戦う姿を<br>モニターさせてもらえないかな？<br><yellow>※ Objetivos enemigos Nv.61+ usando<br>at
Corregido.

2018-03-10 16:54 UTC, Reixaldo commented on Orders/Client/EP4/co04037013.csv
> +Explanation#0,"""やあ、マイフレンド！<br>愛する子供達の成育は順調かい？<br>どの子にも分け隔てなく<br>愛情を注いでいると思うけど<br>僕にその成長ぶりを見せて欲しいんだ！<br>そうだな、今回は<br>君とトリムが共に戦う姿を<br>モニターさせてもらえないかな？<br><yellow>※ Objetivos enemigos Nv.61+ usando<br>at
Corregido.

2018-03-11 07:25 UTC, Reixaldo commented
Hay camello

2018-03-13 01:19 UTC, TheBlazter approved these changes

2018-03-13 01:19 UTC, merged