Update co_031417.csv
Arks-Layer/PSO2ENPatchCSV pull request #594
Opened 2018-07-11 17:11 UTC by SanseiMuramasa

Tutorial translation: Proposed JP > EN translation for 「パートナー好感度」 into "Partner Evaluation"

2018-07-11 18:25 UTC, alama commented
Can you please move the changed file to `Tutorial/Window` folder

2018-07-11 18:29 UTC, SanseiMuramasa commented
I will move it to Tutorial/Window

2018-07-11 19:13 UTC, alama requested changes
the English patch goes for EN-US spelling

2018-07-11 19:13 UTC, alama commented on Tutorial/Window/co_031417.csv
> +text01#0,"""Partner Evaluation<br><br><br>If you clear a quest<br>with a partner character,<br>Or if you complete<br>one of their client orders,<br> That \""Partner Evaluation\"" of you will go up.<b
"Campship", not "campship"

2018-07-11 19:13 UTC, alama commented on Tutorial/Window/co_031417.csv
> +text02#0,"""As your partner's \""Partner Evaluation\"" goes up<br>the \""Present Gague\"" will also go up.<br><br>When that \""Present Gague\"" maxes out<br>That character's will give you<br>their pr
"Gauge", not "Gague"

2018-07-11 19:22 UTC, alama approved these changes

2018-07-12 05:35 UTC, SynthSy commented
Needs to be proofread.

2018-07-12 14:22 UTC, SanseiMuramasa commented
Changed "That character's will give you their present" to "That character will give you their present".

2018-07-12 16:41 UTC, SanseiMuramasa commented
Re-doing the translation for 好感度, as I realized it's not in JP brackets. 「」

I overused the term "Partner Evaluation" in brackets for  好感度. This will be replaced with "character's evaluation" "their evaluation" or "evaluation of you" etc. depending on the context of the situation, plus with no EN brackets.

This will make more sense in plain English as you will see later.

2018-07-12 16:56 UTC, SanseiMuramasa commented
Re-translating 好感度 as "Friendship level", as it seems to be a more appropriate translation.

2018-07-12 17:13 UTC, alama commented on Tutorial/Window/co_031417.csv
> +text01#0,"""Partner's Friendship Level <br><br><br>If you clear a quest<br>with a partner character,<br>Or if you complete<br>one of their client orders,<br> That character's Friendship Level will go
"Freiendship", Should it be "Friendship" like a set of ponies?

2018-07-12 17:34 UTC, SanseiMuramasa commented
The spelling mistake for "Friendship" has been fixed.

2018-07-13 19:25 UTC, SynthSy commented on Tutorial/Window/co_031417.csv
> +text01#0,"""Partner's Friendship Level <br><br><br>If you clear a quest<br>with a partner character,<br>Or if you complete<br>one of their client orders,<br> That character's Friendship Level will go
Or shouldn't be capitalized.

2018-07-13 19:27 UTC, SynthSy commented on Tutorial/Window/co_031417.csv
> +text02#0,"""As your partner's Friendship Level goes up<br>the \""Present Gauge\"" will also go up.<br><br>When that \""Present Gauge\"" maxes out<br>That character will give you<br>their present.<br>
` maxes out<br>That` should be `maxes out, <br>that`

2018-07-13 19:38 UTC, SanseiMuramasa commented on Tutorial/Window/co_031417.csv
> +text02#0,"""As your partner's Friendship Level goes up<br>the \""Present Gauge\"" will also go up.<br><br>When that \""Present Gauge\"" maxes out<br>That character will give you<br>their present.<br>
One more thing.

I translated プレゼントマーク as "Present Icon" because "Present Mark" doesn't seem to make sense in English.

Is this okay?

2018-07-15 19:50 UTC, merged