Es: Craft
Arks-Layer/PSO2ENPatchCSV pull request #684
Opened 2018-12-06 20:09 UTC by Reixaldo

2018-12-06 21:16 UTC, TheBlazter requested changes

2018-12-06 21:16 UTC, TheBlazter commented on UI/ui_craft_name.csv
> +Name_00001#6,"""Espada receta PA 00001"""
Estas lineas ni siquiera están activas en el juego, son mas precisamente lineas hechas como espacios para rellenar en posibles futuros updates, es mejor dejarlas en japones, pueda que nunca las utilicen pero es probable que si las usan al momento de que las usen estas no se actualizaran por la preexistencia de una traducción.

2018-12-06 21:28 UTC, TheBlazter requested changes

2018-12-06 21:28 UTC, TheBlazter commented on UI/ui_craft_name.csv
> +Name_00210#2,"""Rear - Not set 23"""
Mas Lineas de Relleno

2018-12-06 21:28 UTC, TheBlazter commented on UI/ui_craft_name.csv
> +Name_10210#0,"""Arm - Not set 23"""
Lineas de Relleno

2018-12-06 21:28 UTC, TheBlazter commented on UI/ui_craft_name.csv
> +Name_20210#0,"""Leg - Not set 23"""
Lineas de Relleno

2018-12-06 21:36 UTC, Reixaldo commented on UI/ui_craft_name.csv
> +Name_00001#6,"""Espada receta PA 00001"""
Ju... esas lineas las medio tradujimos hace... quizás años...

2018-12-07 00:07 UTC, TheBlazter approved these changes

2018-12-07 00:08 UTC, merged