Es
Arks-Layer/PSO2ENPatchCSV pull request #896
Opened 2019-11-02 00:25 UTC by maxii1996

2019-11-02 00:42 UTC, maxii1996 commented
IDK why gives me error D:

2019-11-02 00:46 UTC, alama commented
Because you changed some of the CSVs in the Files folder? you need to move them out

2019-11-02 00:51 UTC, maxii1996 commented
> Because you changed some of the CSVs in the Files folder? you need to move them out

I dont know what i've done D:

2019-11-02 00:54 UTC, alama commented
No, you do not need to delete them, just rename/move them

2019-11-02 00:56 UTC, maxii1996 commented
but i dont know what the real name is it. And why it change it?
So, I'll start again

2019-11-02 01:10 UTC, alama commented on Files.TODO/co_058010.csv
> +Title#0,"""Inspec. Restos del Otro mundo"""
Why are there 2 `Title#0`?

2019-11-02 01:53 UTC, maxii1996 commented
Thanks you @alama :D

I'm really noob using GitHub i guess xD

2019-11-02 02:34 UTC, alama requested changes
Can not be merged until the CSV files in Files.TODO folder had been moved into suitable folders

2019-11-06 11:07 UTC, maxii1996 commented
@TheBlazter Por favor, dame una mano. Tengo miedo de hacer mas lio D:

2019-11-06 11:18 UTC, maxii1996 commented
Creo que ya está?

2019-11-06 15:18 UTC, alama approved these changes

2019-11-06 15:20 UTC, TheBlazter commented
Thanks @alama for the merge

2019-11-06 15:20 UTC, merged